### ISSUE TITLE
I don't get how to install the new lib

### ISSUE THREAD

**Issue by Darferth** [fo40225/Anaconda-Windows-AMD#2]
As the title says, in your readme you say how to unistall previous versions of numpy, etc but you don't specify the commands or the steps required to install the patched libs. Could you explain how please? I'm new to python and I usually install via pip install command

**Comment by fo40225** [comment]
https://stackoverflow.com/questions/27885397/how-do-i-install-a-python-package-with-a-whl-file

**Comment by Darferth** [comment]
Thank you
