### ISSUE TITLE
Ubuntu workaround

### ISSUE THREAD

**Issue by Cutecatty** [fo40225/Anaconda-Windows-AMD#4]
Thanks a lot fo40225.
I have a 1950x too, is there a workaround ubuntu?

**Comment by fo40225** [comment]
`conda install nomkl`

or build numpy with patch
https://www.agner.org/optimize/#asmlib

**Comment by Cutecatty** [comment]
Thank you, I'll try them out!

**Comment by Cutecatty** [comment]
Dear fo40225,

I tried the nomkl openblas version, it sucks big time on eigenvalues and single value decomposition, other things like determinants and dot products are no where near your level too. Your result is like .....god sent!! 

I have no experience with this level of optimization, so the only way to work around image-augmentations now is to build with your code in windows which is not a friendly platform at all for training neural nets with pytorch, at least for me.

I checked out the resource you linked above, I was like..... gotta train with yoda before facing this vader......

The thing is, you are the only one I saw on the internet that solved this problem......

Now that openblas team are really not gonna deal with threadripper anytime soon.So, is there a chance that you may need to use these libraries in ubuntu?  Lol....
